auto: true
server: true
permalink: none
baseurl: ""
exclude:
- .gitignore
- README.md

prose:
  #rooturl: "_posts"
  rooturl: ""
  metadata:
    _posts/articles: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: jasonruyle
      author: Jason Ruyle
      categories:
      - articles
